# This is a basic workflow to help you get started with Actions

name: Update Moose.lua

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      MYBRANCH: develop

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check branch
        run: |
          echo ${GITHUB_REF_NAME}

      - name: Check if main
        if: ${{github.ref_name=='main'}}
        run: echo I am main as checked by github.ref_name

      - name: Say branch name
        run: echo $MYBRANCH

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: FlightControl-Master/MOOSE_INCLUDE
          ref: develop
          path: ./MooseFiles

      # Runs a single command using the runners shell
      - name: Check Moose files
        run: ls ./MooseFiles

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: ./Missions

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          ls ./Missions

      - name: Unzip File
        run: |
          ls
          unzip "./Missions/Auftrag - 014 - Bombing.miz" -d mission