# This workflow updates the Moose.lua file in all miz files.
name: Update Moose.lua

# Controls when the workflow will run
on:

  # Triggers the workflow on push or pull request events for the "main" and "develop" branches
  push:
    branches:
      - main
      - master
      - develop

  # Triggers the workflow on pull request events for the "main" and "develop" branches
  pull_request:
    branches:
      - main
      - master
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "Update"
  Update:

    # Operating system
    runs-on: ubuntu-latest

    # Set environment variable (not used)
    env:
      BRANCH: main

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Say Mission branch name
      - name: Mission branch
        run: echo ${GITHUB_REF_NAME}

      # Check if main
      - name: Check if main
        if: ${{ github.ref_name=='main' }}
        run: echo "MOOSE_BRANCH=master" >> $GITHUB_ENV

      # Check if master
      - name: Check if master
        if: ${{ github.ref_name=='master' }}
        run: echo "MOOSE_BRANCH=master" >> $GITHUB_ENV

      # Check if develop
      - name: Check if develop
        if: ${{ github.ref_name=='develop' }}
        run: echo "MOOSE_BRANCH=develop" >> $GITHUB_ENV

      # Say Moose branch name.
      - name: Moose branch name
        run: echo $MOOSE_BRANCH

      # Checks-out MOOSE_INCLUDE to ./MooseFiles
      - name: Checkout MOOSE_INCLUDE        
        uses: actions/checkout@v3
        with:
          repository: FlightControl-Master/MOOSE_INCLUDE
          ref: ${{ env.MOOSE_BRANCH }}
          path: ./MooseFiles

      # Checks-out repository to ./self
      - name: Checkout Missions
        uses: actions/checkout@v3
        with: 
          #ref: ${{ env.BRANCH }}
          path: ./self

      # Install python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      # Run python script to update Moose.lua in all miz files
      - name: Run UpdateMoose.py
        run: |
          cd ./self
          python .scripts/UpdateMoose.py ../MooseFiles/Moose_Include_Static/ ./

      # Commit changes      
      - name: Commit Changes
        run: |
          cd ./self
          git add *
          git config --global user.name 'funkyfranky'
          git config --global user.email 'frank@inter-zone.de'
          git commit -am "Updated Moose.lua"
          git push      
