# This is a basic workflow to help you get started with Actions
name: Update Moose.lua

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "Update"
  Update:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      BRANCH: main

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Check branch
        run: |
          echo ${GITHUB_REF_NAME}

      - name: Check if main
        if: ${{github.ref_name=='main'}}
        run: echo I am main as checked by github.ref_name

      - name: Say BRANCH name
        run: echo $BRANCH

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout MOOSE_INCLUDE        
        uses: actions/checkout@v3
        #if: ${{ false }}
        with:
          repository: FlightControl-Master/MOOSE_INCLUDE
          ref: develop
          path: ./MooseFiles

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Self
        uses: actions/checkout@v3
        with: 
          ref: ${{ env.BRANCH }}
          path: ./self

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed      

      # List self directory
      - name: Check Moose files
        run: ls ./self

      - name: Run check.sh
        run: |
          cd ./self
          python check.py ../MooseFiles/Moose_Include_Static/ ./

      - name: Create report file
        run: date +%s > ./self/report2.txt
      
      - name: Commit report
        run: |
          cd ./self
          git add *
          git config --global user.name 'funkyfranky'
          git config --global user.email 'frank@inter-zone.de'
          git commit -am "Automated report"
          git push      
